package dto

const (
	SEARCHING_START int = iota
	SEARCHING_STOP
	SEARCHING_GAME_FOUND // out

	CHATTING_NEW_MESSAGE
	CHATTING_STAGE_IS_OVER // out

	CHOOSING_USERS_CHOSEN
	CHOOSING_STAGE_IS_OVER // out
)
